services:
  backend:
    build: .
    restart: always
    ports:
     - 8080:8080
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
  
volumes:
  pgdata: