# not yet in use
# this file would allow us to configure the service by environment

logging: 
  level: debug

database:
  host: db
  user: dbuser
  password: dbpassword # should be handled in separate secret store
  database: blog
  port: 5432